### ISSUE TITLE
Grammar/Spelling Errors.

### ISSUE THREAD

**Issue by TooPointOhh** [WORMSTweaker/VocaloidMod1.8#1]
I have found a spelling/grammar issue.

On Miku's leek item's lore text it uses the term "eatable" in which the english language primarily uses "edible".

**Comment by WORMSTweaker** [comment]
Woops, will be fixed in the next update >.<
I don't talk english as my main language, so some things might sounds stupid when I write them
Don't blame me please ;-;

**Comment by TooPointOhh** [comment]
Lol no problem. And dont worry, it happens

**Comment by WORMSTweaker** [comment]
So, fixed in the github repo, and on the future update.
Gonna close it now.
